### ISSUE TITLE
what is the meaning of event_date in the gis_line list file?

### ISSUE THREAD

**Issue by xinhuayu** [gadenbuie/covid19-florida#17]
I assume case date is the date FL reported the patient as a case. 

Is the event date related to first clinic visit date or something about test? 

Thanks

-yu

**Comment by gadenbuie** [comment]
I'm not entirely sure myself. The `case` date is mentioned a few times in the information pages about the date, e.g. [here](https://fdoh.maps.arcgis.com/home/item.html?id=f5d69a918fb747019734d9a90cd602f4#overview), but I haven't seen an explanation of the `event_date` variable.

> Q: What does “Case Date” represent?     
>
> “Case date” is the date the positive laboratory result was received in the Department of Health’s database system and became a “confirmed case.” This is not the date a person contracted the virus, became symptomatic, or was treated.  Data users: Please not that case date is stored in the data as “Case_”.

``` r
library(tidyverse)

line_list <- read_csv("https://github.com/gadenbuie/covid19-florida/raw/master/data/covid-19-florida_arcgis_line-list.csv")

line_list %>%
  count(event_date, case) %>%
  ggplot() +
  aes(event_date, case, fill = n) +
  geom_tile() +
  scale_fill_viridis_c(option = "A") +
  theme_minimal() +
  coord_equal()
```

![](https://i.imgur.com/P7qZtya.png)

``` r
line_list %>% 
  select(case, event_date) %>% 
  pivot_longer(cols = c(case, event_date)) %>% 
  ggplot() + 
  aes(x = value) + 
  geom_bar() +
  facet_wrap(vars(name), scales = "free")
```

![](https://i.imgur.com/Xlqdx62.png)

From the [DOH dashboard](https://fdoh.maps.arcgis.com/apps/opsdashboard/index.html#/8d0de33f260d444c852a615dc7837c86):
![image](https://user-images.githubusercontent.com/5420529/80437639-17144180-88d0-11ea-9ccb-a330248ad1c1.png)


<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by xinhuayu** [comment]
thanks.

**Comment by gadenbuie** [comment]
[This article in the Palm Beach Post](https://www.palmbeachpost.com/news/20200505/coronavirus-florida-patients-in-florida-had-symptoms-as-early-as-january?template=ampart) claims that the `event_date` column is patient-reported first day of symptoms.

**Comment by gadenbuie** [comment]
[This article in the Tampa Bay Times](https://www.tampabay.com/news/health/2020/05/05/coranavirus-was-in-florida-before-we-knew-it/) confirms that event date is self-reported symptom onset.

> Reporters discovered an anomaly: Six early cases that had appeared on April 27 did not appear in the May 1 data, including the two cases where symptoms dated back to Dec. 31, 2019. In the May 1 data, the earliest symptom onset date, or “event date,” was listed as Jan 1, 2020.
> 
> Those missing cases were not explained in detail by DOH.
> 
> It is possible that state investigators determined a different symptom onset date for the original cases and updated the data to reflect new findings.
> 
> “Event date will be updated as more information is gathered about the case,” Moscoso, the DOH spokesman, said. “For instance, we would not know the person’s onset date when we received the lab result. The county interviews the individual and determines their onset date, so the ‘event date’ would change.”
