### ISSUE TITLE
county testing data

### ISSUE THREAD

**Issue by xinhuayu** [gadenbuie/covid19-florida#19]
Hi,

I noticed the county testing data stopped updating after April 27. Does that mean the testing data are not available any more?

Thank you very much for your help.

-xyu

**Comment by gadenbuie** [comment]
I'm assuming you're looking at the testing data extracted from the PDF reports. The PDF extraction scripts are very brittle and hard to maintain.

Instead, I would recommend using the data in [data/covid-19-florida_dash_summary.csv](https://github.com/gadenbuie/covid19-florida/blob/master/data/covid-19-florida_dash_summary.csv), specifically the `t_total` column for total testing in each county. This data is pulled directly from the API supporting the dashboard and is definitely more reliable.

Note that there were issues with total testing reported in the afternoon of 2020-05-15 and morning of 2020-05-16.

**Comment by gadenbuie** [comment]
Just to clarify, the issues were with the numbers reported by FL DOH, not my scripts. The test counts reported for many counties were completely (and obviously) wrong.
