### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [gadenbuie/covid19-florida#23]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/CAJYIS
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by gadenbuie** [comment]
I appreciate that you've archived the dataset on Dataverse and I'll try to update it when I can, but I can't commit to keeping it up-to-date. Thanks for letting me know!
