### ISSUE TITLE
7pm Update for 08/31/2020 Missing

### ISSUE THREAD

**Issue by sr1sws** [gadenbuie/covid19-florida#27]
Typically the data is updated about 19:05 everyday for the 2nd daily update. Only a single update is present for 8/31/2020.

Thanks for checking on this!

**Comment by gadenbuie** [comment]
Thanks for letting me know. One of the data files has hit the GitHub 100mb limit, so I'm going to have to go back and manually fix several snapshots before they make it online. I'm also going to need to implement a reasonably future-proof way to keep the data files under 100mb

**Comment by sr1sws** [comment]
Thanks Garrick! Just to let you know, the data archive is very useful. I'm using the zip code level data with our employee zip codes to calculate a percent infected (more or less - 'cause the population by zip code data is stale). This is fed to our executive staff as an additional data point as we work to tune our response. I appreciate you capturing the raw data!

**Comment by gadenbuie** [comment]
Thanks, it's good to hear this is useful to you and others! I haven't had as much time lately to stay on top of changes, so I appreciate you letting me know if anything breaks or changes.

**Comment by sr1sws** [comment]
👍
