### ISSUE TITLE
Cases by zip is no longer public

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/covid19-florida#9]
https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/ArcGIS/rest/services

Now returns an error that a token is required

**Comment by gadenbuie** [comment]
From the [Florida Covid19 Cases ArcGIS overview page](https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/ArcGIS/rest/services/Florida_COVID19_Cases/FeatureServer):

- The map feature service layer for the ZIP CODE data can be accessed here: https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/arcgis/rest/services/Florida_COVID_19_Cases_by_Zip_Code_Area/FeatureServer

    - About page: https://fdoh.maps.arcgis.com/home/item.html?id=300e5ac1f6a84818ba0943ff29101b97#overview

- The hosted table of Zip Code cases, which includes PO Box zip codes, can be accessed here: https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/arcgis/rest/services/Florida_COVID_19_Cases_by_Zip_Code_Area_Table/FeatureServer

    - About page: https://fdoh.maps.arcgis.com/home/item.html?id=093b7d4df3e94af497875e72221f5bc3

**Comment by FeelingMathy** [comment]
I asked about this and got the following answer:
"This layer was corrupted and subsequently deleted. I will check with ESRI and team members to see if there is a way to retrieve the historical version. If you need historical data, further instructions can be given by Nicole Kikuchi by contacting her at Nicole.Kikuchi@FLHealth.gov."

**Comment by gadenbuie** [comment]
Thanks for the update! 

For historical notes, the new URL is https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/arcgis/rest/services/Florida_Cases_Zips_COVID19/FeatureServer/, which shows up on https://open-fdoh.hub.arcgis.com/ but not in the list of FeatureServers from arcgis ([here](https://services1.arcgis.com/CY1LXxl9zlJeBuRZ)).

I found the new link on 2020-05-19 and have been updating the data since then (e3f2fa300d7dbecd876849a3274a86dbb86431f7), which means I don't have historical data from 2020-04-12 through 2020-05-18.
